### ISSUE TITLE
Unexpected transport data binary shape on rpi3

### ISSUE THREAD

**Issue by foggy1** [smartrent/blue_heron#38]
I was able to get the Govee bulb example working from a USB dongle on my PC, hooray! However it was still not working on my Raspberry Pi 3B despite the fact that I confirmed UART was at least able to scan and could clearly see the Govee bulb.

I kept getting this error
```
iex(2)> {:ok, pid} = GoveeBulb.start_link(:uart, %{device: "ttyAMA0"})
{:ok, #PID<0.1301.0>}
** (EXIT from #PID<0.1298.0>) shell process exited with reason: an exception was raised:
    ** (FunctionClauseError) no function clause matching in BlueHeron.ACL.deserialize/1                                                          
        (blue_heron 0.1.0) lib/blue_heron/acl.ex:6: BlueHeron.ACL.deserialize(<<2, 64, 32, 7, 0, 3, 0, 4, 0, 3, 23, 0>>)                         
        (blue_heron 0.1.0) lib/blue_heron/hci/transport.ex:266: BlueHeron.HCI.Transport.ready/3                                                  
        (stdlib 3.13) gen_statem.erl:1166: :gen_statem.loop_state_callback/11                                                                    
        (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3    
```
My guess based on this error on the rpi3, but everything working on USB, was that the rpi3 was just wrong about the `0x2` for some reason, and so transport data that was getting matched in `def ready(:info, {:transport_data, <<0x4, hci::binary>>}, data) do` on my PC was getting caught in the offending stanza above. So, I duplicated the event packet stanza and used it to overshadow the ACL DATA packet stanza, leaving me with the following:

```
  def ready(:info, {:transport_data, <<0x4, hci::binary>>}, data) do
    Logger.hci_packet(:HCI_EVENT_PACKET, :in, hci)

    case handle_hci_packet(hci, data) do
      {:ok, %CommandComplete{} = reply, data} ->
        actions = maybe_reply(data, reply)
        {:keep_state, %{data | caller: nil}, actions}

      {:ok, %CommandStatus{} = reply, data} ->
        actions = maybe_reply(data, reply)
        {:keep_state, %{data | caller: nil}, actions}

      {:ok, _parsed, data} ->
        {:keep_state, data, []}

      {:error, _bin, data} ->
        {:keep_state, data, []}
    end
  end

  def ready(:info, {:transport_data, <<0x2, hci::binary>>}, data) do
    Logger.hci_packet(:HCI_EVENT_PACKET, :in, hci)

    case handle_hci_packet(hci, data) do
      {:ok, %CommandComplete{} = reply, data} ->
        actions = maybe_reply(data, reply)
        {:keep_state, %{data | caller: nil}, actions}

      {:ok, %CommandStatus{} = reply, data} ->
        actions = maybe_reply(data, reply)
        {:keep_state, %{data | caller: nil}, actions}

      {:ok, _parsed, data} ->
        {:keep_state, data, []}

      {:error, _bin, data} ->
        {:keep_state, data, []}
    end
  end

  # def ready(:info, {:transport_data, <<0x2, acl::binary>>}, data) do
  #   Logger.hci_packet(:HCI_ACL_DATA_PACKET, :in, acl)
  #   acl = BlueHeron.ACL.deserialize(acl)
  #   for pid <- data.handlers, do: send(pid, {:HCI_ACL_DATA_PACKET, acl})
  #   :keep_state_and_data
  # end
```

With this configuration, I was able to get it working on the rpi3 as expected, although obviously this is not ideal because I've stomped the ACL protocol by matching all `0x2` as if they are `0x4`.

Would love to take a crack at this if possible, although I'm guessing this is just something about the rpi3 itself? I really have no idea, but wanted to report because one other person confirmed this issue on their rpi3.

**Comment by jjcarstens** [comment]
This workaround just moves the error around. With that new matching function, you're trying to decode as an HCI packet instead of ACL. And the HCI decoder is a little more friendly to let the error go past...

Here's the breakdown of what seems to be happening. TL;DR the packet you're getting back has a length of 1824 bytes, but only 8 bytes are returned, so the match on [`<<..., length::little-16, acl_data::binary-size(length)>>` fails here](https://github.com/smartrent/blue_heron/blob/main/blue_heron/lib/blue_heron/acl.ex#L7)

If I match on the acl_data binary _without_ the size asserted, things complete and show this odd case
```elixir
iex()> <<handle::little-12, pb::2, bc::2, length::little-16, acl_data::binary>> = <<2, 64, 32, 7, 0, 3, 0, 4, 0, 3, 23, 0>>
<<2, 64, 32, 7, 0, 3, 0, 4, 0, 3, 23, 0>>
iex()> handle
1026
iex()> pb
0
iex()> bc
0
iex()> length
1824
iex()> acl_data
<<0, 3, 0, 4, 0, 3, 23, 0>>
```

**Comment by jjcarstens** [comment]
Derp..accidentally hit submit before done typing... 🤦 

So this is just the breakage, but I'm not sure why you have a rogue ACL packet. Even if we get past this, the next step is L2CAP decoding, and it fails there as well so something is awry with this packet coming in (or possibly being decoded)

Do you have the HCI dump of this behavior? That would be most helpful 🙏

**Comment by jjcarstens** [comment]
My current guess to this is that we got a packet fragment because the `Packet_Boundary_Flag` (pb) is 0, which means:

> _First non-automatically-flushable packet of a higher layer message (start of a non-automatically-flushable L2CAP PDU) from Host to Controller_
>
> [Core v5.2 | Vol 4, Part E, section 5.4.2, pg 1893]

Then later it says:

> _The start of a non-flushable packet of a higher layer message (start of a non- automatically-flushable L2CAP PDU) with the PBF of 0b00 shall be transmitted with an LLID of 0b10. All continuing fragment packets of a higher layer message shall be transmitted with an LLID of 0b01._
>
> [Core v5.2 | Vol 4, Part E, section 5.4.2, pg 1894]

This alludes that we should be pulling the LLID from this packet to decide if we need to wait for more packets or append to a previous one. However, I have no idea what the LLID is and how to deal with it here sooool...TBD

**Comment by axelson** [comment]
@jjcarstens Here's a full hcidump.pklg

[dump.zip](https://github.com/smartrent/blue_heron/files/5196797/dump.zip)

**Comment by axelson** [comment]
And here's a more minimal dump after just running `{:ok, pid} = GoveeBulb.start_link(:uart, %{device: "ttyAMA0"})`. Although note that both dumps do include the above patch. I can generate one without that patch if you'd like.

[initial_dump.zip](https://github.com/smartrent/blue_heron/files/5196817/initial_dump.zip)

**Comment by jjcarstens** [comment]
Ah, yes. Can you generate without the patch pleeeease 🙏 ? The patch is incorrectly logging the packet type, so we need it to _not_ pretend it is an HCI_EVENT_PACKET and the expected packet type

**Comment by axelson** [comment]
Okay, here you go!
[without_patch.zip](https://github.com/smartrent/blue_heron/files/5203565/without_patch.zip)

**Comment by axelson** [comment]
And here's the log I got from RingLogger:
<details>
 <summary>Full log</summary>

```
iex(murphy@192.168.1.6)1> RingLogger.attach
:ok
iex(murphy@192.168.1.6)2> {:ok, pid} = GoveeBulb.start_link(:uart, %{device: "ttyAMA0"})
{:ok, #PID<0.1997.0>}

17:13:35.216 [info]  uart-pl011 3f201000.serial: no DMA platform data

17:13:35.223 [info]  Unknown packet for state CONNECT: %BlueHeron.HCI.Event.CommandComplete{
  code: 0xE,
  num_hci_command_packets: 0x1,
  opcode: <<0x3, 0xC>>,
  return_parameters: %{status: <<0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73>>}
}

17:13:35.230 [warn]  (:error, :function_clause) Unable to decode return_parameters for opcode <<0x1, 0x10>>
  return_parameters: <<0, 7, 0, 0, 7, 15, 0, 25, 97>>
  [
  {BlueHeron.HCI.CommandComplete.ReturnParameters.BlueHeron.HCI.Event.CommandComplete,
   :do_decode, [<<1, 16>>, <<0, 7, 0, 0, 7, 15, 0, 25, 97>>],
   [file: 'lib/blue_heron/hci/events/command_complete.ex', line: 38]},
  {BlueHeron.HCI.CommandComplete.ReturnParameters.BlueHeron.HCI.Event.CommandComplete,
   :decode, 1,
   [file: 'lib/blue_heron/hci/events/command_complete.ex', line: 28]},
  {BlueHeron.HCI.Event.CommandComplete, :maybe_decode_return_parameters, 1,
   [file: 'lib/blue_heron/hci/events/command_complete.ex', line: 64]},
  {BlueHeron.HCI.Transport, :handle_hci_packet, 2,
   [file: 'lib/blue_heron/hci/transport.ex', line: 270]},
  {BlueHeron.HCI.Transport, :prepare, 3,
   [file: 'lib/blue_heron/hci/transport.ex', line: 151]},
  {:gen_statem, :loop_state_callback, 11, [file: 'gen_statem.erl', line: 1166]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}
]


17:13:35.231 [info]  Unknown packet for state CONNECT: %BlueHeron.HCI.Event.CommandComplete{
  code: 0xE,
  num_hci_command_packets: 0x1,
  opcode: <<0x1, 0x10>>,
  return_parameters: <<0x0, 0x7, 0x0, 0x0, 0x7, 0xF, 0x0, 0x19, 0x61>>
}

17:13:35.257 [info]  Unknown packet for state CONNECT: %BlueHeron.HCI.Event.CommandComplete{
  code: 0xE,
  num_hci_command_packets: 0x1,
  opcode: <<0x14, 0xC>>,
  return_parameters: %{
    local_name: <<0x42, 0x43, 0x4D, 0x34, 0x33, 0x34, 0x35, 0x43, 0x30>>,
    status: <<0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73>>
  }
}

17:13:35.262 [info]  Unknown packet for state CONNECT: %BlueHeron.HCI.Event.CommandComplete{
  code: 0xE,
  num_hci_command_packets: 0x1,
  opcode: <<0x1, 0xC>>,
  return_parameters: %{status: <<0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73>>}
}

17:13:35.314 [info]  Unknown packet for state CONNECT: %BlueHeron.HCI.Event.CommandComplete{
  code: 0xE,
  num_hci_command_packets: 0x1,
  opcode: <<0x56, 0xC>>,
  return_parameters: %{status: <<0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73>>}
}

17:13:35.317 [info]  Unknown packet for state CONNECT: %BlueHeron.HCI.Event.CommandComplete{
  code: 0xE,
  num_hci_command_packets: 0x1,
  opcode: <<0x18, 0xC>>,
  return_parameters: %{status: <<0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73>>}
}

17:13:35.321 [info]  Unknown packet for state CONNECT: %BlueHeron.HCI.Event.CommandComplete{
  code: 0xE,
  num_hci_command_packets: 0x1,
  opcode: <<0x24, 0xC>>,
  return_parameters: %{status: <<0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73>>}
}

17:13:35.346 [info]  Unknown packet for state CONNECT: %BlueHeron.HCI.Event.CommandComplete{
  code: 0xE,
  num_hci_command_packets: 0x1,
  opcode: <<0x13, 0xC>>,
  return_parameters: %{status: <<0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73>>}
}

17:13:35.351 [warn]  (:error, :function_clause) Unable to decode return_parameters for opcode <<0x45, 0xC>>
  return_parameters: <<0>>
  [
  {BlueHeron.HCI.CommandComplete.ReturnParameters.BlueHeron.HCI.Event.CommandComplete,
   :do_decode, ["E\f", <<0>>],
   [file: 'lib/blue_heron/hci/events/command_complete.ex', line: 38]},
  {BlueHeron.HCI.CommandComplete.ReturnParameters.BlueHeron.HCI.Event.CommandComplete,
   :decode, 1,
   [file: 'lib/blue_heron/hci/events/command_complete.ex', line: 28]},
  {BlueHeron.HCI.Event.CommandComplete, :maybe_decode_return_parameters, 1,
   [file: 'lib/blue_heron/hci/events/command_complete.ex', line: 64]},
  {BlueHeron.HCI.Transport, :handle_hci_packet, 2,
   [file: 'lib/blue_heron/hci/transport.ex', line: 270]},
  {BlueHeron.HCI.Transport, :prepare, 3,
   [file: 'lib/blue_heron/hci/transport.ex', line: 151]},
  {:gen_statem, :loop_state_callback, 11, [file: 'gen_statem.erl', line: 1166]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}
]


17:13:35.352 [info]  Unknown packet for state CONNECT: %BlueHeron.HCI.Event.CommandComplete{
  code: 0xE,
  num_hci_command_packets: 0x1,
  opcode: <<0x45, 0xC>>,
  return_parameters: <<0x0>>
}

17:13:35.359 [warn]  (:error, :function_clause) Unable to decode return_parameters for opcode <<0x7A, 0xC>>
  return_parameters: <<0>>
  [
  {BlueHeron.HCI.CommandComplete.ReturnParameters.BlueHeron.HCI.Event.CommandComplete,
   :do_decode, ["z\f", <<0>>],
   [file: 'lib/blue_heron/hci/events/command_complete.ex', line: 38]},
  {BlueHeron.HCI.CommandComplete.ReturnParameters.BlueHeron.HCI.Event.CommandComplete,
   :decode, 1,
   [file: 'lib/blue_heron/hci/events/command_c
```
</details>

**Comment by ConnorRigby** [comment]
This is actually a bug in the UART transport. I rewrote it and it works now. Will push a PR with the fix soon
